sudo: required
dist: bionic
language: go
go:
  - master
  - 1.13.x
  - 1.14.x

go_import_path: github.com/rh-messaging/shipshape

services:
  - docker

git:
  depth: 1

env:
  global:
    - KUBECONFIG=$HOME/.kube/config
    - KUBERNETES_VERSION=$(curl -k -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)

before_install:
  # Setup kubectl
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/

  # Get tools
  - env GO111MODULE=off go get sigs.k8s.io/kind
  - env GO111MODULE=off go get github.com/jfeliu007/goplantuml/parser
  - env GO111MODULE=off go get github.com/jfeliu007/goplantuml/cmd/goplantuml
  - cd $GOPATH/src/github.com/jfeliu007/goplantuml
  - env GO111MODULE=off go install ./...
  - cd -

  # Create a new Kubernetes cluster using KinD
  - kind create cluster
  - kubectl cluster-info

script:
  - cd $GOPATH/src/github.com/rh-messaging/shipshape
  - make uml
  - env GO111MODULE=on make
  - env GO111MODULE=on make unit-tests
  - env GO111MODULE=on make cluster-test

